set_attribute -quiet [get_net {sys_clk_cts_5_1_BAR}] -name net_type -value clock
set_attribute -quiet [get_net {clk_gate_ram_read_addr_reg/CLK}] -name net_type -value clock
set_attribute -quiet [get_net {clk_gate_ram_write_addr_reg/CLK}] -name net_type -value clock
set_attribute -quiet [get_net {sys_clk_cts_9}] -name net_type -value clock
set_attribute -quiet [get_net {sys_clk_cts_8}] -name net_type -value clock
set_attribute -quiet [get_net {sys_clk_cts_7}] -name net_type -value clock
set_attribute -quiet [get_net {sys_clk}] -name net_type -value clock
set_attribute -quiet [get_net {clk_gate_ram_write_addr_reg/ENCLK}] -name net_type -value clock
set_attribute -quiet [get_net {net23290}] -name net_type -value clock
set_attribute -quiet [get_net {clk_gate_ram_read_addr_reg/ENCLK}] -name net_type -value clock
set_attribute -quiet [get_net {net23284}] -name net_type -value clock
