set_attribute -quiet [get_net {clk}] -name net_type -value clock
set_attribute -quiet [get_net {I_ALU_clk_gate_Lachd_Result_reg/CLK}] -name net_type -value clock
set_attribute -quiet [get_net {I_DATA_PATH_clk_gate_PSWL_Carry_reg/CLK}] -name net_type -value clock
set_attribute -quiet [get_net {I_DATA_PATH_clk_gate_Oprnd_B_reg/CLK}] -name net_type -value clock
set_attribute -quiet [get_net {I_DATA_PATH_clk_gate_Oprnd_A_reg/CLK}] -name net_type -value clock
set_attribute -quiet [get_net {I_INSTRN_LAT_clk_gate_Crnt_Instrn_2_reg/CLK}] -name net_type -value clock
set_attribute -quiet [get_net {I_PRGRM_CNT_TOP_I_PRGRM_CNT_clk_gate_PCint_reg/CLK}] -name net_type -value clock
set_attribute -quiet [get_net {I_STACK_TOP_I_STACK_FSM_clk_gate_TOS_int_reg/CLK}] -name net_type -value clock
set_attribute -quiet [get_net {I_STACK_TOP_I2_STACK_MEM_clk_gate_PopDataOut_reg/CLK}] -name net_type -value clock
set_attribute -quiet [get_net {I_STACK_TOP_I2_STACK_MEM_clk_gate_Stack_Mem_reg_7_/CLK}] -name net_type -value clock
set_attribute -quiet [get_net {I_STACK_TOP_I2_STACK_MEM_clk_gate_Stack_Mem_reg_6_/CLK}] -name net_type -value clock
set_attribute -quiet [get_net {I_STACK_TOP_I2_STACK_MEM_clk_gate_Stack_Mem_reg_5_/CLK}] -name net_type -value clock
set_attribute -quiet [get_net {I_STACK_TOP_I2_STACK_MEM_clk_gate_Stack_Mem_reg_4_/CLK}] -name net_type -value clock
set_attribute -quiet [get_net {I_STACK_TOP_I2_STACK_MEM_clk_gate_Stack_Mem_reg_3_/CLK}] -name net_type -value clock
set_attribute -quiet [get_net {I_STACK_TOP_I2_STACK_MEM_clk_gate_Stack_Mem_reg_2_/CLK}] -name net_type -value clock
set_attribute -quiet [get_net {I_STACK_TOP_I2_STACK_MEM_clk_gate_Stack_Mem_reg_1_/CLK}] -name net_type -value clock
set_attribute -quiet [get_net {I_STACK_TOP_I2_STACK_MEM_clk_gate_Stack_Mem_reg_0_/CLK}] -name net_type -value clock
set_attribute -quiet [get_net {I_STACK_TOP_I2_STACK_MEM_clk_gate_Stack_Mem_reg_0_/ENCLK}] -name net_type -value clock
set_attribute -quiet [get_net {I_STACK_TOP_I2_STACK_MEM_net23085}] -name net_type -value clock
set_attribute -quiet [get_net {I_STACK_TOP_I2_STACK_MEM_clk_gate_Stack_Mem_reg_1_/ENCLK}] -name net_type -value clock
set_attribute -quiet [get_net {I_STACK_TOP_I2_STACK_MEM_net23091}] -name net_type -value clock
set_attribute -quiet [get_net {I_STACK_TOP_I2_STACK_MEM_clk_gate_Stack_Mem_reg_2_/ENCLK}] -name net_type -value clock
set_attribute -quiet [get_net {I_STACK_TOP_I2_STACK_MEM_net23096}] -name net_type -value clock
set_attribute -quiet [get_net {I_STACK_TOP_I2_STACK_MEM_clk_gate_Stack_Mem_reg_3_/ENCLK}] -name net_type -value clock
set_attribute -quiet [get_net {I_STACK_TOP_I2_STACK_MEM_net23101}] -name net_type -value clock
set_attribute -quiet [get_net {I_STACK_TOP_I2_STACK_MEM_clk_gate_Stack_Mem_reg_4_/ENCLK}] -name net_type -value clock
set_attribute -quiet [get_net {I_STACK_TOP_I2_STACK_MEM_net23106}] -name net_type -value clock
set_attribute -quiet [get_net {I_STACK_TOP_I2_STACK_MEM_clk_gate_Stack_Mem_reg_5_/ENCLK}] -name net_type -value clock
set_attribute -quiet [get_net {I_STACK_TOP_I2_STACK_MEM_net23111}] -name net_type -value clock
set_attribute -quiet [get_net {I_STACK_TOP_I2_STACK_MEM_clk_gate_Stack_Mem_reg_6_/ENCLK}] -name net_type -value clock
set_attribute -quiet [get_net {I_STACK_TOP_I2_STACK_MEM_net23116}] -name net_type -value clock
set_attribute -quiet [get_net {I_STACK_TOP_I2_STACK_MEM_clk_gate_Stack_Mem_reg_7_/ENCLK}] -name net_type -value clock
set_attribute -quiet [get_net {I_STACK_TOP_I2_STACK_MEM_net23121}] -name net_type -value clock
set_attribute -quiet [get_net {I_STACK_TOP_I2_STACK_MEM_clk_gate_PopDataOut_reg/ENCLK}] -name net_type -value clock
set_attribute -quiet [get_net {I_STACK_TOP_I2_STACK_MEM_net23126}] -name net_type -value clock
set_attribute -quiet [get_net {I_STACK_TOP_I_STACK_FSM_clk_gate_TOS_int_reg/ENCLK}] -name net_type -value clock
set_attribute -quiet [get_net {I_STACK_TOP_I_STACK_FSM_net23179}] -name net_type -value clock
set_attribute -quiet [get_net {I_PRGRM_CNT_TOP_I_PRGRM_CNT_clk_gate_PCint_reg/ENCLK}] -name net_type -value clock
set_attribute -quiet [get_net {I_PRGRM_CNT_TOP_I_PRGRM_CNT_net23197}] -name net_type -value clock
set_attribute -quiet [get_net {I_INSTRN_LAT_clk_gate_Crnt_Instrn_2_reg/ENCLK}] -name net_type -value clock
set_attribute -quiet [get_net {I_INSTRN_LAT_net23215}] -name net_type -value clock
set_attribute -quiet [get_net {I_DATA_PATH_clk_gate_Oprnd_A_reg/ENCLK}] -name net_type -value clock
set_attribute -quiet [get_net {I_DATA_PATH_net23233}] -name net_type -value clock
set_attribute -quiet [get_net {I_DATA_PATH_clk_gate_Oprnd_B_reg/ENCLK}] -name net_type -value clock
set_attribute -quiet [get_net {I_DATA_PATH_net23239}] -name net_type -value clock
set_attribute -quiet [get_net {I_DATA_PATH_clk_gate_PSWL_Carry_reg/ENCLK}] -name net_type -value clock
set_attribute -quiet [get_net {I_DATA_PATH_net23244}] -name net_type -value clock
set_attribute -quiet [get_net {I_ALU_clk_gate_Lachd_Result_reg/ENCLK}] -name net_type -value clock
set_attribute -quiet [get_net {I_ALU_net23261}] -name net_type -value clock
